apiVersion: v1
kind: Pod
metadata:
  name: payment-service
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo 'Starting...'; sleep 5; exit 1"]
  restartPolicy: Always
